### ISSUE TITLE
CreateProfile on CreateTransactionRequest

### ISSUE THREAD

**Issue by mikewagz** [AuthorizeNet/sdk-ruby#105]
Is it possible to use the createProfile flag currently when running a credit card transaction?  I see it in the API documentation, but it doesn't show here:

[](https://github.com/AuthorizeNet/sdk-ruby/blob/372f4ce1308a9e473f9336689160220c96f5f146/lib/authorize_net/cim/payment_profile.rb)

Here's what I'm trying:

```
    req = CreateTransactionRequest.new
    req.transactionRequest = TransactionRequestType.new()
    req.transactionRequest.transactionType = TransactionTypeEnum::AuthCaptureTransaction
    req.transactionRequest.amount = amount
    req.transactionRequest.payment = PaymentType.new
    req.transactionRequest.payment.opaqueData = OpaqueDataType.new('COMMON.ACCEPT.INAPP.PAYMENT', params[:subscription][:opaque_payment], nil)
    
    req.transactionRequest.profile = PaymentProfile.new(createProfile: true)
```

Here's the response I'm seeing:

```
Transaction Failed
Error Code : E00003
Error Message : The element 'profile' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' has invalid child element 'paymentProfileId' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'. List of possible elements expected: 'createProfile, customerProfileId, paymentProfile, shippingProfileId' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'.
```

**Comment by rahulrnitc** [comment]
Hi @mikewagz 
Currently, it is not possible to createProfile with OpaqueDataType in CreateTransactionRequest(Transaction will succeed, but profile creation will fail). However, you can createProfile with opaqueDataType in CreateCustomerProfile request.

**Comment by mikewagz** [comment]
Thanks @rahulrnitc - I think this will work.  I have succeeded in creating a profile and then running the transaction.  However, I'm wondering if it's possible to verify the payment method prior to creating the profile?

I tried doing a Authorization-Only call with the payment nonce first, to ensure the payment method was valid, followed by creating the profile and then actually processing the transaction.  However, because the nonce is single-use-only, I get the "Invalid OTS" when trying to create the profile with it.

How do you recommend doing this?  Basically I'm trying to give the user an error message first, before creating their profile and saving it, if their payment method is invalid.

Thank you!

**Comment by rahulrnitc** [comment]
Hi @mikewagz,
You can do an AuthCapture transaction with the nonce first and then call CreateCustomerProfileFromTransaction API with that transactionId to create a customer profile. Sample code for this is here: https://github.com/AuthorizeNet/sample-code-ruby/blob/master/CustomerProfiles/create-customer-profile-from-transaction.rb. Hope this answers your question.

**Comment by sizl** [comment]
@rahulrnitc 

is it possible to create a **payment profile** with CreateCustomerProfileFromTransaction ? I'd like to authorize the amount first and then create customer and payment profile.

**Comment by adavidw** [comment]
You can't do that with that call, but can do it with the createTransaction call. Just add the createProfile flag to the transaction request (set to true) and the system will create a profile after doing the transaction (only if the transaction was successful). See more in the [API Reference](https://developer.authorize.net/api/reference/#payment-transactions).

**Comment by sizl** [comment]
Hi @adavidw,


request = AuthorizeNet::API::CreateTransactionRequest.new
request.transactionRequest = AuthorizeNet::API::TransactionRequestType.new
request.transactionRequest.transactionType = AuthorizeNet::API::TransactionTypeEnum::AuthOnlyTransaction
request.transactionRequest.amount = @order.total
request.transactionRequest.currencyCode = 'USD'
request.transactionRequest.createProfile = true


I tried and got this:

undefined method `createProfile=' for #<AuthorizeNet::API::TransactionRequestType:0x007ff11b2719b0>

**Comment by sizl** [comment]
Hi @adavidw,

I found the correct node to set that flag but got this in return:

@text="Customer profile creation failed. This payment method does not support profile creation.",

I think its because im using opaque data. Basically, i just want to save a payment token for future transactions. How can I achieve this while using Accept.js?

**Comment by gauravmokhasi** [comment]
@sizl -- you can pass opaque data fields with data descriptor "COMMON.ACCEPT.INAPP.PAYMENT" in "Create a Customer Profile" and "Create a Payment Profile" API requests, to successfully create payment profiles.

This will save the card that was used to generate the Accept token on file for you. You can then charge these profiles, use them in subscriptions, etc...

You cannot however save the Accept token itself; it is single use.

**Comment by chsriniv9** [comment]
Closing for now based on the suggestion provided by @gauravmokhasi.
Feel free to open if needed.
