### ISSUE TITLE
Version 1.9.2 on rubygems requires activesupport (= 4.2.6)

### ISSUE THREAD

**Issue by iSunRise** [AuthorizeNet/sdk-ruby#108]
Hi, 
I tried to install version `1.9.2` of gem authorizenet from rubygems and run into issue.
For some reason it requires activesupport = 4.2.6 not >= 4.2.6 what makes it impossible to use with rails 5.
I checked gemspec and see that it should require activesupport >= 4.2.6 if RUBY_VERSION > 2.2, but you can see different dependency on [rubygems page](https://rubygems.org/gems/authorizenet/versions/1.9.2).

**Comment by lostapathy** [comment]
#116 will resolve this

**Comment by adavidw** [comment]
We'll hopefully get a new gem cut in the next few days which would resolve this. Stay tuned!

**Comment by lostapathy** [comment]
FYI @iSunRise 1.9.4 has been released which fixes this.
