### ISSUE TITLE
accept.js integration

### ISSUE THREAD

**Issue by ashwinphatak** [AuthorizeNet/sdk-ruby#110]
The code sample for "Create an Accept Payment Transaction" seems to be missing in the repo and hence the docs. Any pointers on usage?

http://developer.authorize.net/api/reference/index.html#payment-transactions-create-an-accept-payment-transaction

![image](https://cloud.githubusercontent.com/assets/14833/26218901/4eb037f2-3c2a-11e7-8760-9c379c2654ec.png)

**Comment by sunnyrajrathod** [comment]
Here is the link to github repo - https://github.com/AuthorizeNet/sample-code-ruby/blob/master/MobileInappTransactions/create-an-accept-transaction.rb
