### ISSUE TITLE
NoMethodError (undefined method 'tax_amount=' for #<AuthorizeNet::Order:0x00557bae7c7048 @tax_exempt=false>)

### ISSUE THREAD

**Issue by chas-mcmahon** [AuthorizeNet/sdk-ruby#130]
I need to access transaction details for payments made via mobile card readers for my app, but I'm running into an error coming from the authorizenet ruby sdk.

First step is to call `get_transaction_details` on an instance of `AuthorizeNet::Reporting::Transaction` to get a response object from the api (an instance of `AuthorizeNet::Reporting::Response`). Next, calling the `transaction` method on `AuthorizeNet::Reporting::Response` yields this error:

`NoMethodError (undefined method 'tax_amount=' for #<AuthorizeNet::Order:0x00557bae7c7048 @tax_exempt=false>):`

The error is thrown from line 93 of `AuthorizeNet::Reporting::Response`

The root of the issue is that the response object expects several attributes to be available on an instance of `AuthorizeNet::Order`, but the class does not declare attr_accessors for them. As far as I know, these are tax_amount, shipping_amount, shipping_name, shipping_description, and duty_amount.

When I modify `AuthorizeNet::Order` in my bundled copy of the gem to declare attr_accessors for those fields, the error disappears and the feature works.

I'd be happy to submit a PR for the issue, though I'm not sure if there are any guidelines for what the maintainers would like to see, particularly around tests. I'm also not sure if there might be some reason behind the bug beyond a simple oversight that might affect what the fix should be. Any help/advice would be much appreciated!

**Comment by adavidw** [comment]
HI @chas-mcmahon,

Thanks for reaching out. I wasn't around when this was first created, so I don't know if there's a good story behind why the accessors aren't there, besides a simple oversight. The best thing to do would be to just add them, so feel free to submit that PR!

As far as testing goes, the [sample code repo](https://github.com/AuthorizeNet/sample-code-ruby) also acts as the main test library. The [sample_code_spec.rb](https://github.com/AuthorizeNet/sample-code-ruby/blob/master/spec/sample_code_spec.rb) file runs the SDK through each of the functions in the sample code files. It would be possible to take one of the samples and modify it to ensure that it's sending values in tax_amount and the others mentioned, and then in the response section add code to access those fields. That would provide a good enough test.

However, if you can't see your way to adding to the sample code, submit the PR anyway. I'll gladly pull it in.

**Comment by chas-mcmahon** [comment]
Thanks for the really quick turnaround @adavidw. I wasn't quite sure what to do with the sample code specs, but I was able to reproduce the error by adding some data to the reporting unit tests and got them passing with the changes.

Let me know if there's anything else I can/should do, and I'll make the necessary changes.

Thanks again for your help!

**Comment by chas-mcmahon** [comment]
@adavidw Do you have an estimate on time to merge the PR and make a new release?

**Comment by namanbansal** [comment]
Merged in https://github.com/AuthorizeNet/sdk-ruby/pull/156/ 
Released in 1.9.5
