### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by chrisamerson** [AuthorizeNet/sdk-ruby#133]
I am getting this message using the sample code as a starting point, and I can't figure out why.

undefined method `creditCard=' for nil:NilClass

Here is my current code:

request = CreateTransactionRequest.new
    request.transactionRequest = TransactionRequestType.new()
    request.transactionRequest.amount = :amount
    request.transactionRequest.payment = PaymentType.new request.transactionRequest.payment.creditCard = CreditCardType.new(:number,"0220",:verification_value)
    request.transactionRequest.transactionType = TransactionTypeEnum::AuthCaptureTransaction

**Comment by adavidw** [comment]
Hi @chrisamerson,

When I copy and paste your code, it looks like you don't have a carriage return between "PaymentType.new" and "request.transactionRequest.payment.creditCard = ". So, the interpreter sees it as all on one line.

Hit enter between those two parts and the error goes away.

**Comment by chrisamerson** [comment]
Wow. That was stupid on my part. Thank you.
