### ISSUE TITLE
Dependent version of 'roxml' gem issues a warning

### ISSUE THREAD

**Issue by gregblass** [AuthorizeNet/sdk-ruby#136]
https://github.com/Empact/roxml/issues/55

/Users/gregblass/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/roxml-3.3.1/lib/roxml/definition.rb:156: warning: constant ::Fixnum is deprecated

The issue is fixed in the roxml library, but it looks like this library is still referencing version 3.3.1 ... exactly. Rare that I see that... any reason for the explicit version there?

In any case, the dependency should be updated to a version of roxml with that fix included.

**Comment by gregblass** [comment]
Not much activity here I guess. Have to say that working with Authorize.Net has been exactly the experience I was hoping that it would not be. Wishing more and more that I just had my client move to Braintree or Stripe.

Anyone actively maintaining this and reading these? Any hope of some action here?

**Comment by gregblass** [comment]
The lack of response here has helped me make the decision to move my client away from authorize.net.

The kicker? $1000 fee to get your information out! Just fantastic. What a fantastic company.

**Comment by anuragg29** [comment]
Hi @gregblass  sorry for the delay response on it . The team has been working on it and the merge for the PR was done today morning . 

Please feel free to reach out to me if any concerns .

**Comment by gregblass** [comment]
Thank you for the response! (genuinely).

FYI (unrelated to this issue) - the other thing that contributed to our decision is that Accept.js requires you to run your local development server using SSL. This is such a PITA to get working with google chrome (look at the stackoverflow issues surrounding it...its a nightmare). It's also just not standard whatsoever for any library to require SSL during development. It made it so I had to start my development server a completely separate way, change the config of my entire app, etc. Just wanted to give you guys a heads up on that.

Other than that, I do really appreciate the response here, as it changed my opinion on Authorize as a company.

**Comment by anuragg29** [comment]
Thanks @gregblass   for the feedback on Accept.js . 

I will suggest to post it as  product improvement idea on our Developer forum under Ideas.

https://community.developer.authorize.net/t5/Ideas/idb-p/ideas 
A place for community members to contribute product ideas and suggestions.

We will definitely look into it to ease the integration for Accept.js .

**Comment by iagopiimenta** [comment]
Any updates on moving this to the master?

**Comment by namanbansal** [comment]
Merged in https://github.com/AuthorizeNet/sdk-ruby/pull/156/  https://github.com/AuthorizeNet/sdk-ruby/pull/156/commits/64183e78708bfdb86cac0b64e433bb4f5cd9c326
Released in 1.9.5
