### ISSUE TITLE
Version bump to resolve warnings?

### ISSUE THREAD

**Issue by lostapathy** [AuthorizeNet/sdk-ruby#153]
Can we bump the version to 1.9.4.1 so that a77c01e8847bcb59fa22091189c4a4f6af67e257 gets included in the release version?

On ruby 2.5 I'm stuck with warnings caused by roxml 3.3.1, being able to use roxml 4.0 to remove those warnings would be much appreciated.

**Comment by varyonic** [comment]
I would prefer that future be merged to master and 1.10.0 be released.

**Comment by lostapathy** [comment]
Correct, all of future should be merged. I don’t care what version number - historically I think they have tried to keep that mostly in sync with their other API releases.

**Comment by varyonic** [comment]
sdk-php has a 1.9.6 already.

**Comment by namanbansal** [comment]
Merged in  https://github.com/AuthorizeNet/sdk-ruby/pull/156/ https://github.com/AuthorizeNet/sdk-ruby/pull/156/commits/64183e78708bfdb86cac0b64e433bb4f5cd9c326
Released in 1.9.5

**Comment by lostapathy** [comment]
thanks @namanbansal !
