### ISSUE TITLE
Customer Profile from a Transaction customerProfileId undefined method `to_xml'

### ISSUE THREAD

**Issue by ianneub** [AuthorizeNet/sdk-ruby#180]
I am getting this error:
```
#<NoMethodError: undefined method `to_xml' for "1969742758":String>
```

When sending a `CreateCustomerProfileFromTransactionRequest` like so:
```ruby
transaction = AuthorizeNet::API::Transaction.new(login_id, tx_key, :gateway => gateway)
	
request = CreateCustomerProfileFromTransactionRequest.new
request.customerProfileId = "1234567"
request.transId = "123456"

res = transaction.create_customer_profile_from_transaction(request)
```

I believe the issue is here:
https://github.com/AuthorizeNet/sdk-ruby/blob/master/lib/authorize_net/api/schema.rb#L3465

Should this not have a type setting of `NumericStringsType` and instead be nothing? According to the [API docs](https://developer.authorize.net/api/reference/index.html#customer-profiles-create-a-customer-profile-from-a-transaction) this is a simple string.

**Comment by gnongsie** [comment]
We are relying on the API specification / XSD as the source of truth, and not the documentation, which may be a bit delayed in updating the details.
In any case, the docs are also in agreement that this field should be a numericString.
I am closing this issue as I do not see it as valid anymore.

**Comment by gnongsie** [comment]
Actually, correction. I must apologize here.
This issue is valid and I will include the fix in my own pull request.
