### ISSUE TITLE
Cannot get bill date from ARB Subscription List

### ISSUE THREAD

**Issue by kevmimcc** [AuthorizeNet/sdk-ruby#23]
Unfortunately Subscription status is almost useless as it doesn't give any details about the subscription, so we are using Get Subscription List.  But we are not able to get the bill-date from that response.  Is it possible to add this feature to the API?

**Comment by brianmc** [comment]
Hi @kevmimcc,  
You're right on Subscription Status.  We've got a ton of API updates around subscriptions in the works and a new "GetSubscriptionDetails" type request is definitely near the top of the priority list.

Keeping this issue open until we get you something you can use.

Brian

**Comment by brianmc** [comment]
New method ARBGetSubscription is coming soon @kevmimcc

**Comment by brianmc** [comment]
Hi @kevmimcc, apologies for not updating this issue when GetSubscription was released back in Nov.  

You can try the method here:  http://developer.authorize.net/api/reference/#recurring-billing-get-subscription 

The Ruby Sample code is here:  https://github.com/AuthorizeNet/sample-code-ruby/blob/master/RecurringBilling/get-subscription.rb
