### ISSUE TITLE
Yank authorize-net from RubyGems

### ISSUE THREAD

**Issue by sl4m** [AuthorizeNet/sdk-ruby#27]
It's a bit confusing to see `authorize-net` and `authorizenet` on RubyGems. In the past, we tried using `authorize-net`, but went with an unofficial, forked version instead because it lacked a feature. I'm trying to use the official version again, but after some digging did I find that your official Ruby gem is called `authorizenet` and on a new version.

http://rubygems.org/gems/authorize-net

**Comment by brianmc** [comment]
Hi @sl4m, we're trying to get in touch with the publisher, we don't want to necessarily ask rubygems to yank it without publisher permission, but we're working on it.

Thanks for the feedback,

Brian

**Comment by sl4m** [comment]
I had assumed `authorize-net` was owned by `AuthorizeNet`. Apologies if that's not the case.
