### ISSUE TITLE
Feature request: give refund to a credit card

### ISSUE THREAD

**Issue by samdvr** [AuthorizeNet/sdk-ruby#28]
The main API supports giving refunds to a credit card with an amount, I was wondering if you could implement that feature.

**Comment by brianmc** [comment]
Hi Sam,

With our new model there's a guaranteed parity between the API & the SDK so I was able to quickly add a sample to show you the partial refund request you mentioned:

https://github.com/AuthorizeNet/sample-code-ruby/blob/master/PaymentTransactions/refund-transaction.rb

You can also read more about the new model here:  https://github.com/AuthorizeNet/sdk-ruby#new-model

Thanks for the issue,

Brian
