### ISSUE TITLE
transaction_details API - unable to get_transaction_list for batch.id

### ISSUE THREAD

**Issue by dmitrypol** [AuthorizeNet/sdk-ruby#29]
I am following instructions on  http://developer.authorize.net/api/transaction_details/ using the https://github.com/AuthorizeNet/sdk-ruby.  When I use http://developer.authorize.net/api/reference/#transaction-reporting-get-transaction-list I get data back.  

Here is my code snippet:

transaction = AuthorizeNet::Reporting::Transaction.new(auth_net_login, auth_net_key, gateway: :production)
response1 = transaction.get_settled_batch_list(DateTime.now() - 7.days, DateTime.now(), true)
batches = response1.batch_list if response1.success?
batches.each do |batch|
  response2 = transaction.get_transaction_list(batch.id)
  transactions = response2.transactions if response2.success?
end

I get the batch IDs (310442465", 310517224, 310608341, 310738305, 310870612) but response2 (get_transaction_list) ALWAYS comes back as nil.  
#<NoMethodError: undefined method `success?' for nil:NilClass>

I can see transaction and batch ID via the GUI.  

I appreciate any advice you can provide.  Thank you.

**Comment by brianmc** [comment]
You need to have a new transaction for each request, see sample below.

Hope this helps,

Brian

````ruby
require 'rubygems'
require 'authorizenet'
  
transaction = AuthorizeNet::Reporting::Transaction.new(auth_net_login, auth_net_key, :gateway => :sandbox)

# Get the batch list

response = transaction.get_settled_batch_list(DateTime.now() - 14.days, DateTime.now(), true)
batches = response.batch_list
puts batches.length.to_s + ' batches in list'

# Get the transaction list

batches.each do |batch|
  puts "Batch ID : #{batch.id}"
  transaction = AuthorizeNet::Reporting::Transaction.new(auth_net_login, auth_net_key, :gateway => :sandbox)

  response2 = transaction.get_transaction_list(batch.id)
  transactions = response2.transactions

  # Get the transaction
  transactions.each do |tx|
    puts "Transaction Status: #{tx.status}"
  end

end
````

**Comment by dmitrypol** [comment]
Thank you very much.  I figured it out.  May I say that the double-meaning of the word transaction is confusing in this case.

**Comment by brianmc** [comment]
Yes I agree with you there!
