### ISSUE TITLE
How do I validate api_login_id and api_transaction_key?

### ISSUE THREAD

**Issue by dmitrypol** [AuthorizeNet/sdk-ruby#34]
Our customer enter their Auth.net credentials into our system.  How can I ping Auth.net to make sure those credentials are valid?  

I can do this 
transaction = AuthorizeNet::AIM::Transaction.new('API_LOGIN', 'API_KEY', :gateway => :...) 
but how do I check the response w/o actually running credit card charge?

**Comment by dmitrypol** [comment]
I received some advice to use AuthenticateTestRequest or Authentication section http://www.authorize.net/support/CIM_XML_guide.pdf but there is no support in SDK for that.  

Any suggestions?  Stripe and WePay support easy ways to validate credentials.

**Comment by brianmc** [comment]
Hi Dmitry,

Our new model should allow for this https://github.com/AuthorizeNet/sdk-ruby#new-model 

If you look in this file there are some existing examples:

https://github.com/AuthorizeNet/sdk-ruby/blob/master/lib/authorize_net/api/transaction.rb

You could just add a new method something like

````ruby
def authenticate_test_request(request)            make_request(request,AuthenticateTestResponse,Type::API_AUTHENTICATE_TEST_REQUEST)
end
````

You can see the request and response are here in https://github.com/AuthorizeNet/sdk-ruby/blob/master/lib/authorize_net/api/schema.rb

Hope this helps, we'll definitely add this to our sdk backlog but also feel free to implement and submit a pull request to us with your change.  

Brian

**Comment by brianmc** [comment]
Added support and rspec for AuthenticateTestRequest  :  https://github.com/AuthorizeNet/sdk-ruby/commit/59d306d3d45a0a74bed8a2f50428f9aeaa1c1e6a

New gem release to follow.
