### ISSUE TITLE
Querying the Transaction Details API by Subscription ID

### ISSUE THREAD

**Issue by dmitrypol** [AuthorizeNet/sdk-ruby#35]
I can now get Subscription IDs through Transaction Details API http://community.developer.authorize.net/t5/The-Authorize-Net-Developer-Blog/ARB-Subscription-IDs-Available-Through-Transaction-Details-API/ba-p/40602
 
But is there a way to query the Transaction Details API by Subscription ID?  We have lots of one time transactions and some recurring subscriptions.  It's much easier to query by Subscription and also less load on Auth.net servers.

**Comment by brianmc** [comment]
There's not Dmitry but it's a really good feature request.  Would you mind adding it in here?  http://community.developer.authorize.net/t5/Ideas/idb-p/ideas  

Thanks,

Brian
