### ISSUE TITLE
Duplicate key in returned_item.rb

### ISSUE THREAD

**Issue by brandoniffert** [AuthorizeNet/sdk-ruby#37]
https://github.com/AuthorizeNet/sdk-ruby/blob/master/lib/authorize_net/reporting/returned_item.rb#L28

```
returned_item = AuthorizeNet::Reporting::ReturnedItem.new({:return_item_id => id, :return_item_date_utc => date_utc, :return_item_date_utc => date_local, :return_item_code => code, :line_item_description => description})
```

`:return_item_date_utc` is duplicated in this hash. Is it supposed to be `:return_item_date_local`?

**Comment by brianmc** [comment]
Closed this one on Future branch, new gem release to follow.
