### ISSUE TITLE
invalid child element 'formOfPayment'

### ISSUE THREAD

**Issue by sheetalank** [AuthorizeNet/sdk-ruby#38]
I am using encryptedtrackdatatype to make a create_transaction request. I am getting the following error message in the response:
@text="The element 'encryptedTrackData' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' has invalid child element 'formOfPayment' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'. List of possible elements expected: 'FormOfPayment' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'

I am not manually creating the xml. So why is it giving me this error? Is there a work around? My code is as follows:
        transaction = Transaction.new('xxxxxx', 'xxxxxxxxxxxx', :gateway => :sandbox)
        request = CreateTransactionRequest.new
        request.transactionRequest = TransactionRequestType.new
        request.transactionRequest.amount = 39.55

        request.transactionRequest.payment = PaymentType.new
        description ="4649443"
        enc_data = "12321321"
        
        scheme = KeyManagementScheme.new(KeyManagementScheme::DUKPT.new(OperationType::DECRYPT, KeyManagementScheme::DUKPT::Mode.new("DECRYPT","1"), KeyManagementScheme::DUKPT::DeviceInfo.new(description), KeyManagementScheme::DUKPT::EncryptedData.new(enc_data)))
        keyblock = KeyBlock.new(KeyValue.new(EncodingType::Base64, EncryptionAlgorithmType::TDES,scheme))
        request.transactionRequest.payment.encryptedTrackData = EncryptedTrackDataType.new(keyblock)
        request.transactionRequest.transactionType = TransactionTypeEnum::AuthCaptureTransaction
        response = transaction.create_transaction(request)

**Comment by sheetalank** [comment]
According to the documentation in the link below, all xml tags for  encryptedTrackData (inside encryptedTrackData tags) have the first letter in uppercase. The gem is not creating a similar xml request.

http://www.authorize.net/support/AIM_guide_XML.pdf

<encryptedTrackData>
<FormOfPayment>
<Value>
<Encoding>Hex</Encoding>
<EncryptionAlgorithm>TDES</EncryptionAlgorithm>
<Scheme>
<DUKPT>
<Operation>DECRYPT</Operation>
<Mode>
<Data>1</Data>
<Mode>
<DeviceInfo>
<Description>
4649443D4944544543482E556E694D61672E416E64726F69642E53646B
76315e536f6d655442444b6579313d736f6d656f7468657276616c756
</Description>
</DeviceInfo>
<EncryptedData>
<Value>
02f300801f342600039b252a343237352a2a2a2a2a2a2a2a353637355e
332f54455354205e2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a3f2a3b343
237352a2a2a2a2a2a2a2a353637353d2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a3f2a
521db2603bfe6169fc371211161c4ad6edd7294a8352af1ba8b388c527d8d6335286413
ad67521b8be085da998cef7ae3621b0b72eecd6d61953a4a268e02a8cdff3d365216df7
3646b326d8dac369c11a2a3a4a9336addc4a15ae5d8843e0163bae895b9b4df3253439b
4dd885363ad108604ea04f2e4fac701a5a0e65c54e1301a5ed7706eb887629949010000
00400015ac1e03
</Value>
</EncryptedData>
</DUKPT>
</Scheme>
</Value>
</FormOfPayment>
</encryptedTrackData>

**Comment by brianmc** [comment]
Hi @sheetalank, you're spot on and we're working on an update for this right now.  

Stay tuned.

**Comment by brianmc** [comment]
Here's a sample of using encrypted data.  Note you will need the code/schema changes in this commit  https://github.com/AuthorizeNet/sdk-ruby/commit/29a1afe8056294159e0993ef0ac7b9b80bad1137  This is future branch so we will update the gem with these changes in our upcoming release.

````ruby
  require 'rubygems'
  require 'authorizenet'

  include AuthorizeNet::API

  transaction = Transaction.new(API_LOGIN_ID, TRANSACTION_KEY, :gateway => :sandbox)
  request = CreateTransactionRequest.new
  request.transactionRequest = TransactionRequestType.new
  request.transactionRequest.amount = 39.55

  request.transactionRequest.payment = PaymentType.new
  request.transactionRequest.payment.encryptedTrackData = EncryptedTrackDataType.new
  request.transactionRequest.payment.encryptedTrackData.FormOfPayment = KeyBlock.new
  request.transactionRequest.payment.encryptedTrackData.FormOfPayment.Value = KeyValue.new
  request.transactionRequest.payment.encryptedTrackData.FormOfPayment.Value.Encoding = EncodingType::Hex
  request.transactionRequest.payment.encryptedTrackData.FormOfPayment.Value.EncryptionAlgorithm = EncryptionAlgorithmType::TDES
  request.transactionRequest.payment.encryptedTrackData.FormOfPayment.Value.Scheme = KeyManagementScheme.new
  request.transactionRequest.payment.encryptedTrackData.FormOfPayment.Value.Scheme.DUKPT = KeyManagementScheme::DUKPT.new
  request.transactionRequest.payment.encryptedTrackData.FormOfPayment.Value.Scheme.DUKPT.Operation = OperationType::DECRYPT
  request.transactionRequest.payment.encryptedTrackData.FormOfPayment.Value.Scheme.DUKPT.Mode = KeyManagementScheme::DUKPT::Mode.new(nil,'1')
  request.transactionRequest.payment.encryptedTrackData.FormOfPayment.Value.Scheme.DUKPT.DeviceInfo = KeyManagementScheme::DUKPT::DeviceInfo.new
  request.transactionRequest.payment.encryptedTrackData.FormOfPayment.Value.Scheme.DUKPT.DeviceInfo.Description = '4649443D4944544543482E556E694D61672E416E64726F69642E53646B7631'
  request.transactionRequest.payment.encryptedTrackData.FormOfPayment.Value.Scheme.DUKPT.EncryptedData = KeyManagementScheme::DUKPT::EncryptedData.new
  request.transactionRequest.payment.encryptedTrackData.FormOfPayment.Value.Scheme.DUKPT.EncryptedData.Value = '02f300801f342600039b252a343237352a2a2a2a2a2a2a2a353637355e332f54455354205e2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a3f2a3b343237352a2a2a2a2a2a2a2a353637353d2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a3f2a521db2603bfe6169fc371211161c4ad6edd7294a8352af1ba8b388c527d8d6335286413ad67521b8be085da998cef7ae3621b0b72eecd6d61953a4a268e02a8cdff3d365216df73646b326d8dac369c11a2a3a4a9336addc4a15ae5d8843e0163bae895b9b4df3253439b4dd885363ad108604ea04f2e4fac701a5a0e65c54e1301a5ed7706eb88762994901000000400015ac1e03'

  request.transactionRequest.retail = TransRetailInfoType.new('2','1')

  request.transactionRequest.transactionType = TransactionTypeEnum::AuthCaptureTransaction

  response = transaction.create_transaction(request)

  if response.messages.resultCode == MessageTypeEnum::Ok
    puts "Successfully made a purchase (authorization code: #{response.transactionResponse.authCode})"
  else
    puts "Failed to make purchase. Error Code : #{response.messages.messages[0].text}"
  end
````

**Comment by brianmc** [comment]
Closing this as supporting gem release is imminent.  Thanks for opening the issue.
