### ISSUE TITLE
Warning message: 'duplicated key'

### ISSUE THREAD

**Issue by ivanovv** [AuthorizeNet/sdk-ruby#40]
Every time I run rails console, I get this warning message:
```gems/authorizenet-1.8.3/lib/authorize_net/reporting/returned_item.rb:28: warning: duplicated key at line 28 ignored: :return_item_date_utc```

**Comment by brianmc** [comment]
Merged PR into Future branch thanks for the update.

https://github.com/AuthorizeNet/sdk-ruby/commit/90748ed4d95a18b48b5f44c1e79cc8a07647134d
