### ISSUE TITLE
Missing Invoice Number for CIM transaction

### ISSUE THREAD

**Issue by dangerouse** [AuthorizeNet/sdk-ruby#41]
When I submit a request to `create_transaction_auth_capture` with an `AuthorizeNet::Order` object that has a value for `#invoice_num`, the value is not showing up in the transaction for my Authorize.net sandbox account.

When I dig a little deeper it seems that the `:invoice_num` is being filtered from the XML generated for submission to AIM. 

It appears that the `AuthorizeNet::Order::Fields` may be [looking for an field called `:invoice_number`](/AuthorizeNet/sdk-ruby/blob/master/lib/authorize_net/fields.rb#L393) when submitting an Order through CIM but [`AuthorizeNet::Order` generates `:invoice_num` field](/AuthorizeNet/sdk-ruby/blob/master/lib/authorize_net/order.rb#L21). 

It's also interesting to note that [a similar setting is defined for `ARB::Fields::SUBSCRIPTION_FIELDS`](/AuthorizeNet/sdk-ruby/blob/master/lib/authorize_net/fields.rb#L199) but it looks for `:invoice_num`.

**Comment by brianmc** [comment]
Thanks @dangerouse we have made the change although technically it's not this PR but same change with a spec to match.

Here's the commit in Future : https://github.com/AuthorizeNet/sdk-ruby/commit/ddc40b0e18b78a19795c3a5149bd423ead671f69


Thanks again,

Brian

**Comment by dangerouse** [comment]
Thanks @brianmc I'll point my app back at master when it's merged. :+1:
