### ISSUE TITLE
#payment_profile_ids always returns nil

### ISSUE THREAD

**Issue by jtrost** [AuthorizeNet/sdk-ruby#47]
I have a user with three payment profiles. I want to retrieve all of the payment profiles. I would think that AuthorizeNet::CIM::Response#payment_profile_ids would return all of the IDs, but it is always nil. Here's some example code.
```ruby
t = AuthorizeNet::CIM::Transaction.new(Rails.application.secrets.authorizenet["api_login_id"], Rails.application.secrets.authorizenet["transaction_key"], gateway: :sandbox)
=> AuthorizeNet::CIM::Transaction
p = t.get_profile(xxxxxxxx)
=> AuthorizeNet::CIM::Response
p.payment_profile_ids
=> nil
```
Calling #payment_profile_id will return only the ID of the first payment profile.
```ruby
p.payment_profile_id
=> "xxxxxxxx"
```
How do I get all of the payment profiles for a specified profile?

**Comment by brianmc** [comment]
Hi @jtrost Apologies for the delay in responding to this one.  We have some sample code for doing just this (you will need gem version 1.8.5.4): https://github.com/AuthorizeNet/sample-code-ruby/blob/master/CustomerProfiles/get-customer-profile.rb

Let us know if this works for you,

Brian
