### ISSUE TITLE
Specs are slow and spammy

### ISSUE THREAD

**Issue by sidonath** [AuthorizeNet/sdk-ruby#6]
Hi!

Considering it takes around 17 minutes to run specs on a decent machine with decent internet connection and that — after running them few times — one gets 78 emails to your inbox, have you maybe considered using [VCR](https://github.com/vcr/vcr) in specs?

**Comment by ashtru** [comment]
Build fixed by PR https://github.com/AuthorizeNet/sdk-ruby/pull/161 . Will reflect in _master_ branch after the next release.

**Comment by chsriniv9** [comment]
This issue is addressed and available in the [sdk-ruby 1.9.6](https://github.com/AuthorizeNet/sdk-ruby/releases/tag/1.9.6)
