### ISSUE TITLE
How can you submit customer meta data along with an AIM transaction request with the ruby gem?

### ISSUE THREAD

**Issue by cannapages** [AuthorizeNet/sdk-ruby#63]
Hello,

This problem used to exist on the old gem and still has not been solved on the official fork. I forked the older authorize gem a while back and hacked it to make it work. I think that most use cases are going to want to store as much information about a customer as possible in the payment gateway?

I was trying to add this feature to your gem or at least figure out how to pass it along using the AIM method. Do you have a recommend way of doing this? It isn't documented and I am certain that many use cases will want to store things like customer name, shipping and billing address and contact information with the transactions.

Thank you.

**Comment by thetyrelcorporation** [comment]
If any one else runs into this we have built an unofficial gem to solve this at https://github.com/thetyrelcorporation/tcorp_authorize.

**Comment by RichardGrossman** [comment]
Try this:

``` 
request.transactionRequest.customer = CustomerType.new()
```

Although there is a bug - it actually sends it as a CustomerDataType.

There's also:
```
 request.transactionRequest.billto = NameAndAddressType.new()
```

The definition of these types is in the gem: schema.rb

**Comment by brianmc** [comment]
You should be able to send all that information along with the transaction using the new model.  Check out our sample code : https://github.com/AuthorizeNet/sample-code-ruby/blob/3652f4610dc5b2aa322e6f723acfe4289f2108d4/PaymentTransactions/charge-credit-card.rb

The sample code shows a few example fields but you can see all the available fields here:  http://developer.authorize.net/api/reference/#payment-transactions-charge-a-credit-card
