### ISSUE TITLE
How to retrieve data after getting response

### ISSUE THREAD

**Issue by Blackening999** [AuthorizeNet/sdk-ruby#73]
this is the clone to
https://github.com/AuthorizeNet/sample-code-ruby/issues/25

"It isn't clear how to "unzip" response and then retrieve data on back-end for further transaction like ARB, doesn't matter actually.
I've tried to do:
```ruby
if response.messages.resultCode == MessageTypeEnum::Ok
     #HERE
      GetCustomerPaymentProfileResponse.new(nil, response.messages, nil, response.paymentProfile)
    else
      puts response.messages.messages[0].text
      raise "Failed to get payment profile information with id #{request.customerPaymentProfileId}"
    end
```
but I can't get any info from it :("

**Comment by brianmc** [comment]
Hi @Blackening999, We've added some additional sample code to https://github.com/AuthorizeNet/sample-code-ruby/blob/master/CustomerProfiles/get-customer-payment-profile.rb 

![image](https://cloud.githubusercontent.com/assets/1022976/11661994/7f260934-9d89-11e5-80f3-0b9fe4cb0c0a.png)


Hope you're ok with closing this one and moving the conversation over to AuthorizeNet/sample-code-ruby#25
