### ISSUE TITLE
Customer payment profile reuse

### ISSUE THREAD

**Issue by Blackening999** [AuthorizeNet/sdk-ruby#75]
Hey guys.

I've seen recent 1.8.7 update and it's great to see your responsiveness.
However, I found another one inconsistency. 

For now it's possible to reuse customer payment profile object (by getting it through the API) when using *charge_client* method. I'm just passing the profile and I don't have to force user enter credit card data again. 

For subscription creation, it isn't possible to pass profile and reuse its data for payment.
The example requires you to pass credit card data and I've tried to retrieve it from the response:
```ruby

 def get_customer_payment_profile(customer_profile_id, customer_payment_profile_id)
    request = GetCustomerPaymentProfileRequest.new
    request.customerProfileId = customer_profile_id
    request.customerPaymentProfileId = customer_payment_profile_id

    response = @@transaction.get_customer_payment_profile(request)


    if response.messages.resultCode == MessageTypeEnum::Ok
      response.paymentProfile
    else
      "Failed to get payment profile information with id #{request.customerPaymentProfileId}"
    end

get_customer_payment_profile(user.customer_profile_id, user.customer_payment_profile_id)
cc_number = customer_payment_profile.payment.creditCard.cardNumber # "XXXX1111" :(
```

You can see that data is masked, so there's no way to direct reuse of this data.

**Comment by namanbansal** [comment]
Hi @Blackening999,
@brianmc mentioned in [this](https://github.com/AuthorizeNet/sample-code-ruby/issues/25) thread that "create subscription from a customer profile" feature will be added in the API very soon.
Will update you when the API supports this.

**Comment by brianmc** [comment]
This will be in the next release of the SDK.

**Comment by brianmc** [comment]
API has been updated to support this: http://developer.authorize.net/api/reference/#recurring-billing-create-a-subscription-from-customer-profile

SDK also updated and sample code available at : https://github.com/AuthorizeNet/sample-code-ruby/blob/master/RecurringBilling/create-subscription-from-customer-profile.rb
