### ISSUE TITLE
Retrieve data from response.transactionResponse.userFields

### ISSUE THREAD

**Issue by RichardGrossman** [AuthorizeNet/sdk-ruby#78]
Created like this:

```
myCustomList = Array.new
myCustomElement = UserField.new('cereal','specialk')
myCustomList.push(myCustomElement)
myCustomElement = UserField.new('coffee','sumatra')
myCustomList.push(myCustomElement)
request.transactionRequest.userFields = UserFields.new(myCustomList)
```

Then what is the syntax to read the value of "cereal' ('specialk") out of the response object?

```
response.transactionResponse.userFields ?
```

I've tried:

```
response.transactionResponse.userFields[0]
response.transactionResponse.userFields(:cereal)
response.transactionResponse.userFields('cereal')
response.transactionResponse.userFields[:name][:cereal]
response.transactionResponse.userFields::name
```
And a lot of similar ruby-style code.

I'm missing some basic principle of ROXML.

**Comment by namanbansal** [comment]
Hi @RichardGrossman ,

Here is a way to access all the userFields in the response:
```ruby
response.transactionResponse.userFields.userFields.each do |userField|
        puts userField.name
        puts userField.value
end
```
What you are trying to do could be done if the response was in a Hash but here we have it in a class.

**Comment by RichardGrossman** [comment]
Thanks!  

Now I see several places where the method or class is repeated - like messages.messages.

Is that because there is a property holding a class, so response.transactionResponse.userFields is a property and it is holding the class userFields (once initialized) ?

**Comment by namanbansal** [comment]
Yes, the property userFields in the response.transactionResponse is of type <b>UserFields</b>, which in turn exposed userFields as an array of <b>UserField</b> and UserField contains the name and value property.

**Comment by RichardGrossman** [comment]
Thanks again.
