### ISSUE TITLE
AuthorizeNet gem namespaces

### ISSUE THREAD

**Issue by RichardGrossman** [AuthorizeNet/sdk-ruby#79]
We (very unfortunately) have a model named "transactions" in our system.  The amount of regression testing, coordination with proven production RAKE CRON jobs, and work to rename that model in an app that is in heavy daily production use would be huge...

require 'authorizenet'
class MyCustomChildClass < MyCustomParentClass
  include AuthorizeNet::API

  def submit_request # payment  # called by another internal method
       api_login_id = params[:name]
       transactionKey = params[transactionKey]

 myTransaction  =  Transaction.new(api_login_id, transactionKey, :gateway => :sandbox) # ERROR
 myTransaction  =  AuthorizeNet::API::Transaction.new(api_login_id, transactionKey, :gateway => :sandbox) # ERROR
 myTransaction  =  AuthorizeNet::AIM::Transaction.new(api_login_id, transactionKey, :gateway => :sandbox) # NO IMMEDIATE ERROR

request = AuthorizeNet::API::CreateTransactionRequest.new  # ERROR
request = AuthorizeNet::CreateTransactionRequest.new  # ERROR

I generated a sample application of my own, and it works fine without the namespace (no transaction table to conflict), and it also works fine with the AuthorizeNet::API namespace.

But our production app does not work.  I've tried a lot of random experiments with no luck.

The only clue is that AuthorizeNet::AIM is visible, but AuthorizeNet:API is not reachable.

Any ideas where I can look to find the source of this problem?

PS:  We've found one laptop where the problem does not occur and another where it does - side-by-side so we're looking at the environment - maybe something that sets load paths...

**Comment by brianmc** [comment]
Hi @RichardGrossman, you didn't mention if you're using Rails, this is a good article if you are : http://urbanautomaton.com/blog/2013/08/27/rails-autoloading-hell/

**Comment by RichardGrossman** [comment]
Thanks - definitive article.

**Comment by RichardGrossman** [comment]
Here's how I solved it:

We already have transaction.rb in app/models.

I created transaction_model.rb in app/models:

class Transactionmodel < Transaction
end

And then in the code for using the gateway, when I need to access our Transaction model, I use Transactionmodel rather than Transaction.

Maybe it's a hack, but it's the easiest and most reliable hack.

**Comment by brianmc** [comment]
Really appreciate you getting back to us with the solution Richard.  That seems to be the standard way of dealing with the collisions in Ruby so at least it's the de facto standard hack.

Thanks again,

Brian
