### ISSUE TITLE
Unable to add email to billing information

### ISSUE THREAD

**Issue by camthompson** [AuthorizeNet/sdk-ruby#95]
When setting `billTo` to a `CustomerAddressType` for a `TransactionRequestType`, I'm able to add all billing information fields except email.

I attempted forking the code to add an email XML accessor to `CustomerAddressType`. I was able to assign the email, but it was not populated in the transaction details.

**Comment by ashtru** [comment]
CreateTransaction API does not support adding email.  You can instead [create a customer profile](https://github.com/AuthorizeNet/sample-code-ruby/blob/master/CustomerProfiles/create-customer-profile.rb#L16) with the email(second field, only one of three is required) then [create a customer payment profile](https://github.com/AuthorizeNet/sample-code-ruby/blob/master/CustomerProfiles/create-customer-payment-profile.rb#L23) of this customer profile. Now, you can create a transaction [charging this customer payment profile](https://github.com/AuthorizeNet/sample-code-ruby/blob/master/PaymentTransactions/charge-customer-profile.rb#L20&L21). You can follow the samples codes for this purpose. If you have any further questions, feel free to ask.

**Comment by brianmc** [comment]
Also, although we don't recommend using the legacy customer object in createTransaction you can do that if you absolutely don't want to create a customer profile. e.g.
request.transactionRequest.customer = CustomerType.new(nil,'cust_email.mail.com')
