### ISSUE TITLE
How to add invoice field to Transaction Request and Subscription Requests

### ISSUE THREAD

**Issue by zberkom** [AuthorizeNet/sdk-ruby#96]
On Authorize, I can see the text invoice field, which I want to use to pass the type of donation that is being submitted. 

After spending awhile reading through the source code, I don't see the invoice field on either the Transaction Request or the Subscription Request objects. Is there a way to submit that field to Authorize using this gem?

**Comment by ashtru** [comment]
In CreateSubscription [request](http://developer.authorize.net/api/reference/index.html#recurring-billing-create-a-subscription), you can pass an order field, which has invoiceNumber and description fields. In your case, description field should serve the purpose.

**Comment by zberkom** [comment]
@ashtru Great, just what I needed. Thanks!
